### ISSUE TITLE
`goto` and `GetResponse` methods don't work in Python 3.11

### ISSUE THREAD

**Issue by alfred-exe** [kramcat/CharacterAI#1]
The underscore in the method names inside the pyCAI class prevents it from working or something, but removing the underscore seems to make it work fine. 

There is also the fact that when c.ai is overloaded, it simply gives you an error instead of waiting until it gains access to the site.

**Comment by kramcat** [comment]
Thanks for the information about the bug, uninstall and install the new version of the library 

In the next version of the library, I will wait for a response when the site is overloaded

**Comment by kramcat** [comment]
check new version, I added new parameter `wait`

`client.user.info(wait=True)`

and it will be waiting for response
