### ISSUE TITLE
the character AI isn't responding to me back 

### ISSUE THREAD

**Issue by Tenztan** [kramcat/CharacterAI#10]
![aaaa](https://github.com/kramcat/CharacterAI/assets/114846712/16cd17c7-df2c-440c-a216-1a95eb61586b)
when i input , the code just run without giving error but it is also not responding to my input , like i waited 30 min after inputting and  it doesn't do anything ;-;. hope you can help!

**Comment by kramcat** [comment]
I will fix all bugs with user.send_message() in the next few days, it will be in version 0.4.0

**Comment by Tenztan** [comment]
thanks for the help , update me when it works it would be great help!

**Comment by kramcat** [comment]
`chat.send_message()` has been rewritten In v0.4.0

**Comment by kramcat** [comment]
`chat.send_message()` has been rewritten In v0.4.0

**Comment by SrKlono** [comment]
still not working here using pip package v0.4.1
