### ISSUE TITLE
AttributeError: "Profile" has no attribute "model_validate"

### ISSUE THREAD

**Issue by Nytro69** [kramcat/CharacterAI#114]
I've searched through the characterai Lib, but no mention of model_validate. The Error comes from the get_me() method: 

`class Account:
    @caimethod
    async def get_me(self, *, token: str = None):
        """Information about your account

        EXAMPLE::

            await client.get_me()

        Returns:
            :obj:`~characterai.types.account.Profile`
        """
        data = await self.request(
            'chat/user/', token=token
        )

        name = data['user']['user']['username']

        if name == 'ANONYMOUS':
            return account.Anonymous()
        elif name.startswith('Guest'):
            return account.Guest.model_validate(
                flatten(data)
            )

        return account.Profile.model_validate(
            flatten(data)
        )`

And this is the Profile class:

`class Profile(BaseModel, Avatar):

    name: str
    avatar_type: str
    onboarding_complete: bool
    avatar_file_name: str | None
    mobile_onboarding_complete: int | None
    bio: str | None
    username: str
    id: int
    first_name: str | None
    is_staff: bool
    subscription: int | None
    is_human: bool
    email: str
    needs_to_acknowledge_policy: bool
    suspended_until: datetime | None
    hidden_characters: List[str]
    blocked_users: List[str]`

**Comment by PanosEZ** [comment]
I have had this issue for a while as well, after some long time of figuring out a fix I finally found what was causing the problem. it has to do with the pydantic library.

The model_validate method is not available in pydantic version 1.x. This method was introduced in pydantic version 2.0. Upgrade pydantic to version 2.x for compatibility with the characterai package.

pydantic 2.x introduced several changes and improvements over 1.x. The model_validate method is part of these changes and replaces some of the previous methods used for model validation.

**upgrade pydantic:**
`pip install --upgrade pydantic`

**Comment by Nytro69** [comment]
> I have had this issue for a while as well, after some long time of figuring out a fix I finally found what was causing the problem. it has to do with the pydantic library.
> 
> The model_validate method is not available in pydantic version 1.x. This method was introduced in pydantic version 2.0. Upgrade pydantic to version 2.x for compatibility with the characterai package.
> 
> pydantic 2.x introduced several changes and improvements over 1.x. The model_validate method is part of these changes and replaces some of the previous methods used for model validation.
> 
> **upgrade pydantic:** `pip install --upgrade pydantic`

Thank you so much,
