### ISSUE TITLE
click response error

### ISSUE THREAD

**Issue by mutethecat** [kramcat/CharacterAI#12]
retrying click action, attempt #56
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="modal-body">…</div> from <div tabindex="-1">…</div> subtree intercepts pointer events
retrying click action, attempt #57
  waiting 500ms

**Comment by endrizzimarco** [comment]
I am getting the same error, what did you do to fix it?

**Comment by kramcat** [comment]
Fixed in v0.5.0
