### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by superalix** [kramcat/CharacterAI#15]
Bot gives an "500 Internal Server Error" after several success attempts to reply. Earlier versions of the library did not have this error. Can i fix this?

**Comment by kramcat** [comment]
«A 500 internal server error is, as the name implies, a general problem with the website's server. More than likely, this means there's an issue or temporary glitch with the website's programming» - Google

This is not an error of the library or your code, but a site error

**Comment by lstanford53** [comment]
I also sometimes get 500 errors. I get them when I try to chat with a character I didn't make. However, if I try it with a character I made, it works perfectly fine. Something must be messed up on CharacterAI's site.
