### ISSUE TITLE
AttributeError: 'character' object has no attribute 'new_chat'

### ISSUE THREAD

**Issue by mangoo-14** [kramcat/CharacterAI#26]
when i try to use the "new_chat" thing it gives me this error. 
![image](https://github.com/kramcat/CharacterAI/assets/122029246/2f9cca18-d690-41fe-b25b-be5f69794355)
![image](https://github.com/kramcat/CharacterAI/assets/122029246/128633dc-8c0b-4139-aa29-837c7b6b992f)

**Comment by kramcat** [comment]
documentation problem, fixed

`client.chat.new_chat(...)`
