### ISSUE TITLE
I want host a bot with the api but...

### ISSUE THREAD

**Issue by LucasAlgerDay** [kramcat/CharacterAI#27]
![image](https://github.com/kramcat/CharacterAI/assets/88118098/08539fdc-e79c-4bc6-a301-48de032ff16d)
i cant install the drivers, some alternative?

**Comment by LucasAlgerDay** [comment]
the host is squarecloud

**Comment by KubaPro010** [comment]
If you have a CMD or a terminal just enter "playwright install", if you cant then just contact the hosting service, it's not kramcat's fault, it's playwright
