### ISSUE TITLE
Markdown styling is ignored

### ISSUE THREAD

**Issue by alfred-exe** [kramcat/CharacterAI#3]
This library ignores if text is *italicized* or **in bold** on c.ai's site. I've also noticed that interaction with new lines is finnicky.
To put this issue into perspective, if the character says "Haha!

*I get up.*" on the site, it shows up like this when printed: "Haha!
*​*
*​*
*​*
*​*
I get up."

**Comment by kramcat** [comment]
Thanks for watching, I'll try to find the tags responsible for text formatting and insert them into the response

**Comment by kramcat** [comment]
Markdown is available in version 0.4.0
