### ISSUE TITLE
PyAsyncCAI.chat.send_message() prints 'none' to the console

### ISSUE THREAD

**Issue by SeoulSKY** [kramcat/CharacterAI#30]
I found that this line prints 'none' to the console, which is frustrating :(

https://github.com/kramcat/CharacterAI/blob/b02cda143a375a676aba8bc6554a426b7afa0f5e/characterai/pyasynccai.py#L385

**Comment by Fadlay** [comment]
bro, how to get pyCAI('TOKEN') ?

**Comment by SeoulSKY** [comment]
It's described right on the description https://pycai.gitbook.io/welcome/api/values

**Comment by SeoulSKY** [comment]
> bro, how to get pyCAI('TOKEN') ?

It's described right on the description https://pycai.gitbook.io/welcome/api/values

**Comment by kramcat** [comment]
fixed in v0.7.0
