### ISSUE TITLE
module object is not callable???

### ISSUE THREAD

**Issue by RamenTheDoodler** [kramcat/CharacterAI#31]
```
Traceback (most recent call last):
  File "c:\Users\_____\OneDrive\Documents\discordbots\aigeneratedtogrps\caitest.py", line 38, in <module>
    asyncio.run(main())
  File "C:\Users\_____\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\_____\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\_____\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\_____\OneDrive\Documents\discordbots\aigeneratedtogrps\caitest.py", line 7, in main
    caiclient = pyasynccai("7b9773bac6c2a3139dd41e393fce72f76d9e9342")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
```
![image](https://github.com/kramcat/CharacterAI/assets/121641643/08413028-08e1-4d7c-9304-032555ccb083)
i copied the exact code from the gitbook (other than renaming the client and making it a  global variable but it shouldn't be the issue, right?)

**Comment by RamenTheDoodler** [comment]
also i apologize if this is a duplicate issue

**Comment by SeoulSKY** [comment]
pyasynccai refers to the 'pyasynccai.py' module, not the class 'PyAsyncCAI'.
Replace pyasynccai with PyAsyncCAI

**Comment by RamenTheDoodler** [comment]
`NameError: name 'PyAsyncCAI' is not defined. Did you mean: 'pyasynccai'?`
i replaced the part with the function call but now i get this error

**Comment by SeoulSKY** [comment]
Did you import the class?

**Comment by RamenTheDoodler** [comment]
i installed the library with pip, was there something else i needed to do for it to work or?

**Comment by SeoulSKY** [comment]
You need to import the class in order to create its instances. Add this statement to the top of the file

from characterai import PyAsyncCAI

**Comment by RamenTheDoodler** [comment]
boy do i feel stupid. all i forgot to do was capitalize PyAsyncCAI because i had typed it as "pyasynccai"
