### ISSUE TITLE
What does "KeyError: 'src_char'" mean?

### ISSUE THREAD

**Issue by Bahman-sudo** [kramcat/CharacterAI#32]
So, I wanted to see if this would be a means to bypass the filter on character.ai,
But, when I did do that, occasionally, I would get `name = data['src_char']['participant']['name'] KeyError: 'src_char'`

What does this mean?

**Comment by KubaPro010** [comment]
The filter is on the server-side, and so the server instead of the normal message returns a message that doesn't have anything that you could expect, **you can't bypass the filter**
