### ISSUE TITLE
Keep getting error AttributeError: module 'characterai.errors' has no attribute 'NoResponse' 

### ISSUE THREAD

**Issue by Double-L5** [kramcat/CharacterAI#33]
Every time I use the example code or anything else involving the API I get the error: AttributeError: module 'characterai.errors' has no attribute 'NoResponse'

**Comment by Michael7575** [comment]
Having the same issue

**Comment by sambitweeting** [comment]
I am also facing same issue. Can you please look into it.

**Comment by SeoulSKY** [comment]
I made a pull request regarding this issue. Hopefully it gets merged soon

**Comment by kramcat** [comment]
fixed on v0.8.0
