### ISSUE TITLE
I am so confused by everything

### ISSUE THREAD

**Issue by Dekriel** [kramcat/CharacterAI#35]
What do all of these keys mean?
<img width="317" alt="image" src="https://github.com/kramcat/CharacterAI/assets/92822789/8ba64909-b813-4139-9026-9be0bc31a6b5">
only few of them are actually specified, and the documentation doesn't do anything to help.

**Comment by RodnoiD1m0n** [comment]
i simply printed the responces(in this case variable "history") before writing other part about iterating through history

**Comment by kramcat** [comment]
I will update the documentation, you can output function responses, so you can understand what is needed for what

**Comment by Dekriel** [comment]
I've managed to sort it out in the end. :)
