### ISSUE TITLE
It looks like you are using Playwright Sync API inside the asyncio loop

### ISSUE THREAD

**Issue by RodnoiD1m0n** [kramcat/CharacterAI#36]
i sometimes get error "It looks like you are using Playwright Sync API inside the asyncio loop." on `client = PyCAI(auth_token)`. i do not use async so i guess it is related to how this package works.

i noticed it happens only when CharacterAI(website) is overloaded(e.g. when waiting queue appears) but more frequently i get `TimeoutError`(which is logical). setting "wait" to true does not help either

**Comment by 2kjiejie** [comment]
Same here

**Comment by kramcat** [comment]
try on v0.8.0
