### ISSUE TITLE
I don't know how to get the Token

### ISSUE THREAD

**Issue by TitanProgrammer4480** [kramcat/CharacterAI#37]
There's no part in the documentation where he writes what for a token it is and how to get it. Please help.

**Comment by SylesGH** [comment]
Go to [character.ai](character.ai) then press Ctrl+Shift+J there will be an Applications tab. Click on that and find local storage. There's a key starts with an @ click on that and find the access token in the body. Copy the access token

**Comment by SeoulSKY** [comment]
Here's the [part](https://pycai.gitbook.io/welcome/api/values) that explains how to get the token.

**Comment by kramcat** [comment]
you can also go to DevTools on browser go to Storage -> Local Storage -> char_token and copy "value"

**Comment by fbpsysadm** [comment]
@kramcat this key is not there anymore ?  thanks...

chat_token
![image](https://github.com/kramcat/CharacterAI/assets/136929380/ccfb7fee-7299-47f3-8371-fca17271bca4)

**Comment by tominal** [comment]
Yep. Doesn't look like this thing works at all anymore.

![image](https://github.com/kramcat/CharacterAI/assets/8497308/9269d9c0-a935-4df1-9d00-114049612270)
