### ISSUE TITLE
There's a problem with token and the character

### ISSUE THREAD

**Issue by SylesGH** [kramcat/CharacterAI#38]
```
Traceback (most recent call last):
  File "C:\Users\hp\Documents\Projects\python\chatbot\c.ai.py", line 20, in <module>
    data = client.chat.send_message('YntB_ZeqRq2l_aVf2gWDCZl4oBttQzDvhj9cXafWcF8', message, wait=True)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\characterai\characterai.py", line 383, in send_message
    info = PostResponse(
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\characterai\characterai.py", line 82, in PostResponse
    raise errors.ServerError(response.status_text)
characterai.errors.ServerError: Unauthorized
```

Why am I getting this and I couldn't find the token from the network tab so I used local storage and copied the access token in the key that starts with **@@auth0spajs**

Are some characters are blocked or something else because I can write in [character.ai](character.ai) easily with no problem

`@kramcat @kramcat @kramcat`

**Comment by SeoulSKY** [comment]
I highly suspect that your token is invalid. My token consists of only random numbers and alphabets, not @@ or auth

**Comment by SylesGH** [comment]
No I mean it's in the application tab in the developer panel. Because I couldn't find it in the network

**Comment by SeoulSKY** [comment]
> No I mean it's in the application tab in the developer panel. Because I couldn't find it in the network

Try using Firefox as in the document

**Comment by KubaPro010** [comment]
Try opening the site normally and opening any request from the network tab and see if it has a `Authorization` header, remove the `Bearer ` prefix, and you have the token

**Comment by EliMCGamerGuy** [comment]
Using firefox, tried what the documentation said to do, authentication key did not show up, even after I chatted with a bot.

**Comment by kramcat** [comment]
In DevTools on browser go to Storage -> Local Storage -> char_token and copy "value"
