### ISSUE TITLE
characterai.errors.ServerError: Not Found

### ISSUE THREAD

**Issue by Sorio6** [kramcat/CharacterAI#44]
```
from characterai import PyCAI

client = PyCAI("MyToken", headless=False)

char = "2T3Xhqf5B_b9Wrn8Bg0FeCYR7BPx2LtJQJJCIB4Qe18" # hyperglot

chat = client.chat.get_chat(char)
```

When opening the browser, I see the tab name "Chat now with HyperGlot" but the window closes with these error message

> characterai.errors.ServerError: Not Found

>  Traceback (most recent call last):
>   File "c:\Users\gsapp\Documents\prog\python\Hope\CAi_test.py", line 7, in <module>
>     chat = client.chat.get_chat(char)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\gsapp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\characterai\characterai.py", line 362, in get_chat
>     return PostResponse(
>            ^^^^^^^^^^^^^
>   File "C:\Users\gsapp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\characterai\characterai.py", line 82, in PostResponse
>     raise errors.ServerError(response.status_text)
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Can you help me ?

Thanks in advance.

**Comment by kramcat** [comment]
maybe you don't have a chat with this character

**Comment by Sorio6** [comment]
Thank you and I'm sorry to have bothered you. 
This question had such a simple answer.

Sorry and thanks again.
