### ISSUE TITLE
cannot use client.chat.get_chat(char)

### ISSUE THREAD

**Issue by rxwf001** [kramcat/CharacterAI#48]
I'm following the chatting code example on documentation. I'm having the following error when I use client.chat.get_chat(char):

Obs.: I'm using venv

Traceback (most recent call last):
    chat = client.chat.get_chat(roxy_char)
  File "D:\files\cai api\venv\lib\site-packages\characterai\characterai.py", line 567, in get_chat
    return _PostResponse(
  File "D:\files\cai api\venv\lib\site-packages\characterai\characterai.py", line 58, in _PostResponse
    _goto('', wait=wait, token=token)
  File "D:\files\cai api\venv\lib\site-packages\characterai\characterai.py", line 22, in _goto
    raise errors.UnknownError(E)
characterai.errors.UnknownError: 'NoneType' object has no attribute 'goto'

**Comment by KubaPro010** [comment]
Did you use the `client.start()` func?, If no then add a line after defining the client that runs the function

**Comment by kubanemil** [comment]
Be sure that char variable is the string, kinda similar to this: 
`char = "EEI6sjnddRIJTVC59MODiYjL0-JyDIVI2IEGLkPx2Jk"`
You can find it in the URL of the chat bot:
https://beta.character.ai/chat?char=EEI6sjnddRIJTVC59MODiYjL0-JyDIVI2IEGLkPx2Jk

**Comment by KubaPro010** [comment]
@kubanemil If the character id would be invalid then there would be a different error, `NotFound` , I think

**Comment by kramcat** [comment]
fixed on v0.8.0
