### ISSUE TITLE
Doesn't work with discord.py

### ISSUE THREAD

**Issue by sillbillgato** [kramcat/CharacterAI#53]
![main_file](https://github.com/kramcat/CharacterAI/assets/145267933/5988bb37-4aa9-4350-afeb-7f11b102f18e)
![cai_file](https://github.com/kramcat/CharacterAI/assets/145267933/c1efb876-1606-4aae-975d-414bc927020a)
for some reason removing "from cai import cai_request" line fixes the problem

**Comment by kramcat** [comment]
Why you using sync PyCAI with async discord bot

**Comment by sillbillgato** [comment]
k sorry im dumb, thanks for fast response
