### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by st4rted** [kramcat/CharacterAI#55]
I'm confused. Why are you using `playwright`? Is it because of Cloudflare? If so, you can simply bypass it so people don't have to install `playwright`. It's not difficult, and I do it all the time, lol.

**Comment by KubaPro010** [comment]
Character uses a V2 cloudflare challenge, which requires JS, cookies

**Comment by st4rted** [comment]
> Character uses a V2 cloudflare challenge, which requires JS, cookies

I bypassed it without using either of those.

**Comment by KubaPro010** [comment]
Mhm, sending a post request that's bypassed? With what?

**Comment by st4rted** [comment]
> Mhm, sending a post request that's bypassed? With what?

Yeah, have you ever heard of `tls_client`? Well, try it out next time before talking. It literally bypasses Character.AI's Cloudflare.

**Comment by kramcat** [comment]
The day before yesterday I was able to bypass cloudflare using tls_client. The library is almost ready, today or tomorrow I will post an update

**Comment by KubaPro010** [comment]
@st4rted Looks like no, i'm gonna check it out, thanks

**Comment by st4rted** [comment]
> The day before yesterday I was able to bypass cloudflare using tls_client. The library is almost ready, today or tomorrow I will post an update without Playwright

I pretty much already finished a version without `playwright`.

**Comment by kramcat** [comment]
fixed on v0.8.0
