### ISSUE TITLE
Add to documentation how to get the tgt value

### ISSUE THREAD

**Issue by rainwashed** [kramcat/CharacterAI#58]
The documentation has no where specific mentioning the retrival of the tgt value. Add this code under the https://pycai.gitbook.io/welcome/api/values "tgt" section which retrives the tgt value:

```py
PyCai("token").chat.get_chat("char")["participants"][0]["user"]["username"] if not PyCai("token").chat.get_chat("char")[
    "participants"][0]["is_human"] else PyCai("token").chat.get_chat("char")["participants"][1]["user"]["username"]
```

**Comment by gregorybednov** [comment]
Thank you, that's great solution! It works fine!

But here is a rewritten version that seems to be easier to understand:

```python
token = "HERE IS ACCOUNT TOKEN" # TODO
char_id = "HERE IS CHARACTER ID" # TODO

client = PyCAI("token")

tgt = client.chat.get_chat(char_id)["participants"][0]["user"]["username"] if not client.chat.get_chat(char_id)[
    "participants"][0]["is_human"] else client.chat.get_chat(char_id)["participants"][1]["user"]["username"]

print(tgt)

```

Now it does not mix that "user" is just a JSON field but "char" is a parameter needed to be changed.
And yes, then I run this code, I got a string with `internal_id:here:is-some-hex-digits-and-delimiters`, that's okay that it has internal_id at beginning.

**Comment by rainwashed** [comment]
👍 Good idea

**Comment by kramcat** [comment]
Added! https://docs.kram.cat/qna.html#what-s-tgt
