### ISSUE TITLE
pyAsyncCAI is bugged

### ISSUE THREAD

**Issue by Zerowack** [kramcat/CharacterAI#6]
AttributeError: 'NoneType' object has no attribute 'goto'

**Comment by kramcat** [comment]
Thanks for finding the bug. Please write your code and version of the library, and version of python

This bug does not reproduce for me, I have python3.9

**Comment by KubaPro010** [comment]
You need to use the .start() method. (https://github.com/kramcat/CharacterAI/blob/main/characterai/pyasynccai.py, line 49)

**Comment by Zerowack** [comment]
I figured it out, thanks!
