### ISSUE TITLE
KeyError: 'turn'

### ISSUE THREAD

**Issue by GatorGamer** [kramcat/CharacterAI#60]
![image](https://github.com/kramcat/CharacterAI/assets/130500031/30d1ff75-18aa-4a2a-ba24-ffe90ae57bfd)
I keep getting this error it worked fine the first time I ran it but then the second time this error started popping up

**Comment by kramcat** [comment]
Maybe it's a filter, check your chat

**Comment by kramcat** [comment]
the error is outdated and most likely fixed
