### ISSUE TITLE
Can not get token anymore

### ISSUE THREAD

**Issue by tominal** [kramcat/CharacterAI#71]
![image](https://github.com/kramcat/CharacterAI/assets/8497308/99989e5f-a0ab-41a0-b562-6206d8c13ab0)

https://pycai.gitbook.io/welcome/api/values

Anybody have any ideas or is this thing dead?

**Comment by PrizeGotti** [comment]
I just grabbed mine from local storage (1st set on instructions, still works). Once you have your token you shouldn't need it again. Your token doesn't change. I've been using the same token for a couple of months, and checking my local storage it hasn't changed.

**Comment by tominal** [comment]
Ah, Jesus. You have to be logged in. I did not see that in the documentation given c.ai works just by simply visiting a page.

#72
