### ISSUE TITLE
Error when chatting with a new Character.

### ISSUE THREAD

**Issue by K0sh1R1zumu** [kramcat/CharacterAI#74]
Whenever I start a chat with a character that I have no previous history of chatting with, I encounter an Exception with the JSONDecodeError.
The Raise Exception is:
```
Exception has occurred: JSONDecodeError
Expecting value: line 2 column 1 (char 1)
StopIteration: 1

During handling of the above exception, another exception occurred:

  File "C:\Users\User\Test\app.py", line 9, in <module>
    chat = client.chat.get_chat(char)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```
I read from a previous issue that this exception is only raised when the server of CharacterAI is either down or overloaded. But this doesn't seem to be the case in this error.

**Comment by ConfirmDev** [comment]
Hi, I just now trying this project and its worked, after see ur issue I realised something in the character char,

![image_2023-12-12_024823626](https://github.com/kramcat/CharacterAI/assets/104125152/261c76f4-6ccd-416e-831a-e9236e0e89a4)
Some character have link pattern like this, its use 'chat'.

![image](https://github.com/kramcat/CharacterAI/assets/104125152/be5759b7-aeb1-4e0e-ab8d-b2470a861a1d)
But when you try a character that used 'chat2', its doesnt work anymore.

Maybe you should try other character that use old pattern. Btw, sorry for my bad english.

**Comment by ConfirmDev** [comment]
use this instead, sorry this is from my project but its worked. :

`
from characterai import PyAsyncCAI

client = PyAsyncCAI("TOKEN_HERE")
char = "CHAR_HERE"
user_message = input("Input: ")

chat = await client.chat2.get_chat(char)        
author = {'author_id': chat['chats'][0]['creator_id']}
async with client.connect() as chat2:
    data = await chat2.send_message(char, chat['chats'][0]['chat_id'], user_message, author)
            
print(data['turn']['candidates'][0]['raw_content'])
`

**Comment by Karvp** [comment]
Hi there,
Your error is caused by the server's response to a new character **without any chat with you**. Please look at the response below:
`there is no history between user and character`
Yes, it came with a **404** error and is not in JSON format; that's why there is an error. To fix this, you should try to maintain the library on your own to handle this error.
