### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by SSL-ACTX** [kramcat/CharacterAI#77]
Hello, I kept having this problem when I switch to certain characters, Hu Tao, Character Assitant, and Stella works fine, but Raiden and other characters doesn't work at all and gives this error:

![image](https://github.com/kramcat/CharacterAI/assets/120081647/48e1a745-d935-4523-9f01-0db90c2ff197)

Here's my code:

```
from characterai import PyCAI

client = PyCAI('my-token')

char = "RQrrOj-UNdEV2_PC5D03US-27MZ7EUtaRH_husjbRQA"

chat = client.chat.get_chat(char)

participants = chat['participants']

if not participants[0]['is_human']:
    tgt = participants[0]['user']['username']
else:
    tgt = participants[1]['user']['username']

while True:
    message = input('You: ')

    data = client.chat.send_message(
        chat['external_id'], tgt, message
    )

    name = data['src_char']['participant']['name']
    text = data['replies'][0]['text']

    print(f"{name}: {text}")
```

**Comment by Karvp** [comment]
As I suggested in [this issue](https://github.com/kramcat/CharacterAI/issues/74#issuecomment-1854012664), the server's response to the API request *may not be in the form of JSON*, and that caused the exception. There might be several reasons for this (e.g., not found, unauthorized, invisible character, etc.). I encourage you to *debug the library code* to find out the error.

**Comment by SSL-ACTX** [comment]
I see. Thanks for the response.
