### ISSUE TITLE
Timeout while waiting for element

### ISSUE THREAD

**Issue by Polymecha** [kramcat/CharacterAI#8]
Waits for 30 seconds after I ask something, then shows this 
![image](https://user-images.githubusercontent.com/73960880/236525252-ddd9fded-0d74-42f4-9463-6f7fc1b365d4.png)

**Comment by kramcat** [comment]
Thanks for finding the bug, please send me your code, python version and library version

**Comment by Polymecha** [comment]
Version 3.10.6
Currently using the placeholder code with some minor configuration changes (testing for now)
![image](https://user-images.githubusercontent.com/73960880/236552507-8396a84b-6688-4d69-937a-4d04a71bc9de.png)
![image](https://user-images.githubusercontent.com/73960880/236552682-98914860-08ee-4b42-bd0a-1cccd951e5d6.png)

**Comment by kramcat** [comment]
You can also check your token via user.info (), if it says that you are anonymous, then you entered the wrong token

**Comment by Polymecha** [comment]
Nope. Not anonymous.

**Comment by kramcat** [comment]
`chat.send_message()` has been rewritten In v0.4.0
