### ISSUE TITLE
What is Response 403

### ISSUE THREAD

**Issue by Algoroxyolo** [kramcat/CharacterAI#82]
![image](https://github.com/kramcat/CharacterAI/assets/53085041/b2a504dd-075f-4cfe-b6eb-ed88e23028e0)

I am sure that my key is correct but i am keep getting response 403

**Comment by SeoulSKY** [comment]
I'm getting the same response. Response 403 means your request is forbidden. It returns "Content-Type": text/html, which I believe it's a Capcha page by reading the response body.

**Comment by kr91416** [comment]
A 403 response code means that the site you are trying to access is forbidden. This is probably a loophole so that somebody cannot steal the code.

**Comment by kramcat** [comment]
This bug is due to Cloudflare, fixed in the new version
