### ISSUE TITLE
doesnt work anymore (verifying you are human error)

### ISSUE THREAD

**Issue by hexgeissinger** [kramcat/CharacterAI#84]
I have a project i made using this library that used to work perfectly fine, but now when I run my code it takes me to a page that says "Verifying you are human. This may take a few seconds." it then reloads again and again. I assume they put this here to thwart libraries like this? Or is there a workaround?

**Comment by Karvp** [comment]
Well, I have the same issue. I just update the tls-client library to the newest version and everything solved
