### ISSUE TITLE
Argument of type "str" cannot be assigned

### ISSUE THREAD

**Issue by FalcoTK** [kramcat/CharacterAI#85]
```
char = input("input char: ")
chat = client.chat.get_chat(char) #<< here the erorr
```
then how do I fix it, after I run it once it can't be run again

**Comment by Karvp** [comment]
Can you provide more detail like the traceback, etc.

**Comment by FalcoTK** [comment]
![WhatsApp Image 2024-02-25 at 7 02 51 AM](https://github.com/kramcat/CharacterAI/assets/160510985/527340c6-d5e5-493c-905a-772677aa765c)

like this?

**Comment by Karvp** [comment]
What version of python are u using? Or did u enable type checking in vscode? disable it, in the init of PyCAI, chat has been overwritten with itself, vsc is wrong

**Comment by KubaPro010** [comment]
No, that not the problem, hover over it of you have intellisense (vs code feature), here you have "char" so put in `client.chat.get_chat(char=char)`, did notice that its because the class isn't initiated

**Comment by Karvp** [comment]
@KubaPro010 you should notice that the `chat` subclass is there in PyCAI. The creator use that same name so it makes Pylance confuse, (vsc also). Anyway, your fix is correct.

**Comment by FalcoTK** [comment]
> @Karvp No, that not the problem @FalcoTK hover over it of you have intellisense (vs code feature), here you have "char" so put in `client.chat.get_chat(char=char)`, did notice that its because the class isn't initiated
arl bro, thank you :D

**Comment by FalcoTK** [comment]
done
