### ISSUE TITLE
code: 'ERR_UNHANDLED_REJECTION'

### ISSUE THREAD

**Issue by Dragonslayer22x** [kramcat/CharacterAI#87]
node js: Received message: below.
node js: [node_characterai] Puppeteer - Eval-fetching is an experimental feature and may be slower. Please report any issues on github
node js: node:internal/process/promises:289
node js:             triggerUncaughtException(err, true /* fromPromise */);
node js:             ^
node js:
node js: [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
node js:   code: 'ERR_UNHANDLED_REJECTION'
node js: }
node js:
node js: Node.js v20.11.1

**Comment by artificialbutter** [comment]
This looks like you might be opening this issue in the wrong repository. This appears to be an error from node_characterai, which you can find at https://github.com/realcoloride/node_characterai. This repository is for the python characterai library.

**Comment by kramcat** [comment]
This does not refer to this repository.
