### ISSUE TITLE
How do I get the char_token after the new character.ai update?

### ISSUE THREAD

**Issue by TheJoetube** [kramcat/CharacterAI#92]
I tried to follow the steps provided to get the char token but I doesn't exist, is there an alternative way?

**Comment by Karvp** [comment]
You are using the [new character.ai site](https://character.ai/) (not [beta.character.ai](https://beta.character.ai) or [plus.character.ai](https://plus.character.ai)), aren't u? If so, just go back to the old site and login with the same account, the code will work again.

**Comment by TheJoetube** [comment]
> You are using the [new character.ai site](https://character.ai/) (not [beta.character.ai](https://beta.character.ai) or [plus.character.ai](https://plus.character.ai)), aren't u? If so, just go back to the old site and login with the same account, the code will work again.

that worked, thanks!

**Comment by Momenx1** [comment]
but they will close the old c.ai website soon?

**Comment by cdubya15** [comment]
I cannot access the old website anymore. When I enter "beta.character.ai" it redirects me to the new site. I cannot locate the char.token value from there, unless I am missing something?
