### ISSUE TITLE
tls_client.exceptions.TLSClientExeption

### ISSUE THREAD

**Issue by longanhe** [kramcat/CharacterAI#94]
When I run the case given on the official website. I first replaced the token and role ID, but the following error was returned to me..
`tls_client.exceptions.TLSClientExeption: failed to do request: Post "https://beta.character.ai/chat/history/continue/": read tcp 192.168.2.68:62628->104.18.223.226:443: wsarecv: An existing connection was forcibly closed by the remote host.`

**Comment by kramcat** [comment]
Check with the new version
